"""empty message

Revision ID: 77b9ac30e7a5
Revises: 1ca8230b6d83
Create Date: 2021-12-23 11:31:40.530758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b9ac30e7a5'
down_revision = '1ca8230b6d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followers', type_='foreignkey')
    # ### end Alembic commands ###
